name: バグ報告
description: バグや不具合を報告する
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: バグの内容を簡潔に記述してください
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期待される動作
      description: 本来どのように動作すべきかを記述してください
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット
      description: あればスクリーンショットを添付してください
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: 原因・修正案
      description: 検討がついている場合は記述してください
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 参考情報
      description: その他、参考になる情報があれば記述してください
    validations:
      required: false
