name: Fix（修正提案）
description: コードの改善、リファクタリング、小さな問題の修正を提案する
title: "[Fix] "
labels: ["fix"]
body:
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: 修正が必要な現状を記述してください
    validations:
      required: true

  - type: textarea
    id: concern
    attributes:
      label: 懸念点
      description: 提案する機能や改善で懸念点があれば記述してください
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 参考情報
      description: その他、参考になる情報があれば記述してください
    validations:
      required: false
